const { supabase } = require('./_supabase');
const { PDFDocument, StandardFonts, rgb } = require('pdf-lib');
const { Resend } = require('resend');
const crypto = require('crypto');

const resend = new Resend(process.env.RESEND_API_KEY);

function trunc(str, max) {
  if (!str) return '';
  return str.length > max ? str.slice(0, max - 1) + '…' : str;
}

async function appendAuditPage(pdfDoc, document, signers) {
  const page = pdfDoc.addPage([595, 842]); // A4
  const { width, height } = page.getSize();

  const bold    = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const regular = await pdfDoc.embedFont(StandardFonts.Helvetica);

  const blue      = rgb(0.118, 0.251, 0.686);
  const dark      = rgb(0.10,  0.10,  0.10);
  const gray      = rgb(0.45,  0.45,  0.45);
  const white     = rgb(1,     1,     1);
  const lightBlue = rgb(0.937, 0.949, 0.996);
  const lightGray = rgb(0.961, 0.965, 0.976);
  const lineColor = rgb(0.882, 0.914, 0.941);

  // ── Header band ──────────────────────────────────────────────────
  page.drawRectangle({ x: 0, y: height - 72, width, height: 72, color: lightBlue });
  page.drawText('Document Signing Certificate', {
    x: 40, y: height - 38, size: 18, font: bold, color: blue,
  });
  page.drawText('Issued by SignFlow  ·  Tamper-evident audit trail', {
    x: 40, y: height - 58, size: 9, font: regular, color: gray,
  });

  let y = height - 100;

  // ── Document details ─────────────────────────────────────────────
  page.drawText('DOCUMENT DETAILS', { x: 40, y, size: 9, font: bold, color: blue });
  y -= 8;
  page.drawLine({ start: { x: 40, y }, end: { x: width - 40, y }, thickness: 0.5, color: lineColor });
  y -= 18;

  const detailRow = (label, value, yPos) => {
    page.drawText(label, { x: 40, y: yPos, size: 10, font: bold, color: dark });
    page.drawText(value, { x: 130, y: yPos, size: 10, font: regular, color: dark });
  };

  detailRow('Name:',        trunc(document.name, 65), y); y -= 16;
  detailRow('Document ID:', document.id,              y); y -= 16;
  detailRow('Completed:',   new Date().toUTCString(), y);

  y -= 32;

  // ── Signing log ───────────────────────────────────────────────────
  page.drawText('SIGNING LOG', { x: 40, y, size: 9, font: bold, color: blue });
  y -= 8;
  page.drawLine({ start: { x: 40, y }, end: { x: width - 40, y }, thickness: 0.5, color: lineColor });
  y -= 18;

  const col1 = 50, col2 = 190, col3 = 365;
  const rowH = 20;

  // Table header
  page.drawRectangle({ x: 40, y: y - 4, width: width - 80, height: rowH, color: blue });
  page.drawText('Signer Name',    { x: col1, y: y + 3, size: 9, font: bold, color: white });
  page.drawText('Email Address',  { x: col2, y: y + 3, size: 9, font: bold, color: white });
  page.drawText('Signed At (UTC)',{ x: col3, y: y + 3, size: 9, font: bold, color: white });
  y -= rowH + 2;

  // Table rows
  signers.forEach((s, i) => {
    if (i % 2 === 0) {
      page.drawRectangle({ x: 40, y: y - 4, width: width - 80, height: rowH, color: lightGray });
    }
    const ts = s.signed_at ? new Date(s.signed_at).toUTCString() : '—';
    page.drawText(trunc(s.name  || '', 22), { x: col1, y: y + 3, size: 9, font: regular, color: dark });
    page.drawText(trunc(s.email || '', 26), { x: col2, y: y + 3, size: 9, font: regular, color: dark });
    page.drawText(ts,                       { x: col3, y: y + 3, size: 9, font: regular, color: dark });
    y -= rowH + 2;
  });

  y -= 24;

  // ── Integrity notice ──────────────────────────────────────────────
  page.drawText('INTEGRITY & VERIFICATION', { x: 40, y, size: 9, font: bold, color: blue });
  y -= 8;
  page.drawLine({ start: { x: 40, y }, end: { x: width - 40, y }, thickness: 0.5, color: lineColor });
  y -= 16;

  const notice = [
    'This document has been cryptographically fingerprinted using SHA-256.',
    'The fingerprint is stored securely in our records and uniquely identifies this exact file.',
    'Any modification to this document — including this page — will invalidate the fingerprint.',
    'To verify authenticity, share the Document ID with the issuing party.',
  ];
  notice.forEach(line => {
    page.drawText(line, { x: 40, y, size: 9, font: regular, color: gray });
    y -= 14;
  });

  // ── Footer ────────────────────────────────────────────────────────
  page.drawLine({ start: { x: 40, y: 35 }, end: { x: width - 40, y: 35 }, thickness: 0.5, color: lineColor });
  page.drawText(
    'This certificate was automatically generated by SignFlow and forms part of the signed document.',
    { x: 40, y: 20, size: 8, font: regular, color: gray }
  );
}

async function generateFinalPDF(docId) {
  const { data: blob, error } = await supabase.storage
    .from('documents')
    .download(`pdfs/${docId}/document.pdf`);
  if (error) throw error;

  const pdfDoc = await PDFDocument.load(Buffer.from(await blob.arrayBuffer()));
  const firstPage = pdfDoc.getPages()[0];
  const { width } = firstPage.getSize();

  const { data: signers } = await supabase
    .from('signers')
    .select('name, email, signed_at, signature_data, sig_x, sig_y, sig_w, sig_h')
    .eq('doc_id', docId)
    .order('signed_at', { ascending: true });

  // Embed each signer's signature at their designated field
  for (const signer of signers) {
    if (!signer.signature_data) continue;

    const sigBuffer = Buffer.from(signer.signature_data.split(',')[1], 'base64');
    const isJpeg = signer.signature_data.startsWith('data:image/jpeg') ||
                   signer.signature_data.startsWith('data:image/jpg');
    const sigImage = isJpeg
      ? await pdfDoc.embedJpg(sigBuffer)
      : await pdfDoc.embedPng(sigBuffer);

    if (signer.sig_x != null) {
      firstPage.drawImage(sigImage, {
        x: signer.sig_x, y: signer.sig_y,
        width: signer.sig_w, height: signer.sig_h,
      });
    } else {
      const sw = width * 0.25;
      const sh = sigImage.height * (sw / sigImage.width);
      firstPage.drawImage(sigImage, { x: width - sw - 20, y: 30, width: sw, height: sh });
    }
  }

  // Fetch document metadata for audit page
  const { data: document } = await supabase
    .from('documents')
    .select('id, name')
    .eq('id', docId)
    .single();

  // Append audit trail page
  await appendAuditPage(pdfDoc, document, signers);

  const finalBuffer = Buffer.from(await pdfDoc.save());

  // SHA-256 fingerprint of the complete final PDF
  const hash = crypto.createHash('sha256').update(finalBuffer).digest('hex');

  const { error: uploadError } = await supabase.storage
    .from('documents')
    .upload(`pdfs/${docId}/final.pdf`, finalBuffer, {
      contentType: 'application/pdf',
      upsert: true,
    });
  if (uploadError) throw uploadError;

  return { buffer: finalBuffer, hash };
}

async function emailFinalPDF(docId, finalBuffer) {
  const { data: document } = await supabase.from('documents').select('name').eq('id', docId).single();
  const { data: signers }  = await supabase.from('signers').select('email').eq('doc_id', docId);

  for (const signer of signers) {
    await resend.emails.send({
      from: process.env.FROM_EMAIL,
      to: signer.email,
      subject: `Fully Signed: "${document.name}"`,
      html: `
        <div style="font-family:sans-serif;max-width:600px;margin:0 auto;">
          <h2 style="color:#166534;">All Parties Have Signed</h2>
          <p>The document <strong>${document.name}</strong> has been signed by all parties.</p>
          <p>Please find the fully signed document attached. The last page is a signing certificate with a tamper-evident audit trail.</p>
        </div>
      `,
      attachments: [{
        filename: `signed_${document.name}`,
        content: finalBuffer,
      }],
    });
  }
}

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).end();

  const { token, signatureData } = req.body;

  try {
    const { data: tokenRow, error: tokenError } = await supabase
      .from('tokens')
      .select('*')
      .eq('token', token)
      .single();

    if (tokenError || !tokenRow) return res.status(404).json({ error: 'Invalid token' });

    if (new Date(tokenRow.expiry) < new Date()) {
      return res.status(410).json({ error: 'Signing link has expired' });
    }

    const { doc_id: docId, signer_id: signerId } = tokenRow;

    const { data: signer } = await supabase.from('signers').select('status').eq('id', signerId).single();
    if (signer.status === 'signed') {
      return res.status(400).json({ error: 'Already signed' });
    }

    await supabase.from('signers').update({
      status: 'signed',
      signed_at: new Date().toISOString(),
      signature_data: signatureData,
    }).eq('id', signerId);

    const { data: allSigners } = await supabase
      .from('signers')
      .select('status')
      .eq('doc_id', docId);

    const allSigned = allSigners.every(s => s.status === 'signed');

    if (allSigned) {
      const { buffer: finalBuffer, hash } = await generateFinalPDF(docId);
      await supabase.from('documents')
        .update({ status: 'completed', final_hash: hash })
        .eq('id', docId);
      await emailFinalPDF(docId, finalBuffer);
    }

    res.status(200).json({ success: true, allSigned });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
}
